import React from "react";
import Select from "react-select";
const CountryOptions = () => {
  const options = [
    { value: "0", label: "Afeganistão" },
    { value: "1", label: "Ilhas Åland" },
    { value: "2", label: "Albânia" },
    { value: "3", label: "Argélia" },
    { value: "4", label: "Samoa Americana" },
    { value: "5", label: "Andorra" },
    { value: "6", label: "Angola" },
    { value: "7", label: "Anguila" },
    { value: "8", label: "Antártida" },
    { value: "9", label: "Antígua e Barbuda" },
    { value: "10", label: "Argentina" },
    { value: "11", label: "Armênia" },
    { value: "12", label: "Aruba" },
    { value: "13", label: "Austrália" },
    { value: "14", label: "Áustria" },
    { value: "15", label: "Azerbaijão" },
    { value: "16", label: "Bahamas" },
    { value: "17", label: "Bahrein" },
    { value: "18", label: "Bangladesh" },
    { value: "19", label: "Barbados" },
    { value: "20", label: "Bielorrússia" },
    { value: "21", label: "Bélgica" },
    { value: "22", label: "Belize" },
    { value: "23", label: "Benin" },
    { value: "24", label: "Bermudas" },
    { value: "25", label: "Butão" },
    { value: "26", label: "Bolívia" },
    { value: "27", label: "Bósnia e Herzegovina" },
    { value: "28", label: "Botsuana" },
    { value: "29", label: "Ilha Bouvet" },
    { value: "30", label: "Brasil" },
    { value: "31", label: "Território Britânico do Oceano Índico" },
    { value: "32", label: "Brunei" },
    { value: "33", label: "Bulgária" },
    { value: "34", label: "Burkina Faso" },
    { value: "35", label: "Burundi" },
    { value: "36", label: "Camboja" },
    { value: "37", label: "Camarões" },
    { value: "38", label: "Canadá" },
    { value: "39", label: "Cabo Verde" },
    { value: "40", label: "Ilhas Cayman" },
    { value: "41", label: "República Centro-Africana" },
    { value: "42", label: "Chade" },
    { value: "43", label: "Chile" },
    { value: "44", label: "China" },
    { value: "45", label: "Ilha do Natal" },
    { value: "46", label: "Ilhas Cocos (Keeling)" },
    { value: "47", label: "Colômbia" },
    { value: "48", label: "Comores" },
    { value: "49", label: "Congo" },
    { value: "50", label: "República Democrática do Congo" },
    { value: "51", label: "Ilhas Cook" },
    { value: "52", label: "Costa Rica" },
    { value: "53", label: "Costa do Marfim" },
    { value: "54", label: "Croácia" },
    { value: "55", label: "Cuba" },
    { value: "56", label: "Chipre" },
    { value: "57", label: "República Tcheca" },
    { value: "58", label: "Dinamarca" },
    { value: "59", label: "Djibuti" },
    { value: "60", label: "Dominica" },
    { value: "61", label: "República Dominicana" },
    { value: "62", label: "Equador" },
    { value: "63", label: "Egito" },
    { value: "64", label: "El Salvador" },
    { value: "65", label: "Guiné Equatorial" },
    { value: "66", label: "Eritreia" },
    { value: "67", label: "Estônia" },
    { value: "68", label: "Etiópia" },
    { value: "69", label: "Ilhas Malvinas" },
    { value: "70", label: "Ilhas Faroe" },
    { value: "71", label: "Fiji" },
    { value: "72", label: "Finlândia" },
    { value: "73", label: "França" },
    { value: "74", label: "Guiana Francesa" },
    { value: "75", label: "Polinésia Francesa" },
    { value: "76", label: "Territórios Franceses do Sul" },
    { value: "77", label: "Gabão" },
    { value: "78", label: "Gâmbia" },
    { value: "79", label: "Geórgia" },
    { value: "80", label: "Alemanha" },
    { value: "81", label: "Gana" },
    { value: "82", label: "Gibraltar" },
    { value: "83", label: "Grécia" },
    { value: "84", label: "Groenlândia" },
    { value: "85", label: "Granada" },
    { value: "86", label: "Guadalupe" },
    { value: "87", label: "Guam" },
    { value: "88", label: "Guatemala" },
    { value: "89", label: "Guernsey" },
    { value: "90", label: "Guiné" },
    { value: "91", label: "Guiné-Bissau" },
    { value: "92", label: "Guiana" },
    { value: "93", label: "Haiti" },
    { value: "94", label: "Ilhas Heard e McDonald" },
    { value: "95", label: "Vaticano" },
    { value: "96", label: "Honduras" },
    { value: "97", label: "Hong Kong" },
    { value: "98", label: "Hungria" },
    { value: "99", label: "Islândia" },
    { value: "100", label: "Índia" },
    { value: "1.1", label: "Indonésia" },
    { value: "1.2", label: "Irã" },
    { value: "1.3", label: "Iraque" },
    { value: "1.4", label: "Irlanda" },
    { value: "1.5", label: "Ilha de Man" },
    { value: "1.6", label: "Israel" },
    { value: "1.7", label: "Itália" },
    { value: "1.8", label: "Jamaica" },
    { value: "1.9", label: "Japão" },
    { value: "2.0", label: "Jersey" },
    { value: "2.1", label: "Jordânia" },
    { value: "2.2", label: "Cazaquistão" },
    { value: "2.3", label: "Quênia" },
    { value: "2.4", label: "Quiribati" },
    { value: "2.5", label: "Coreia do Norte" },
    { value: "2.6", label: "Coreia do Sul" },
    { value: "2.7", label: "Kuwait" },
    { value: "2.8", label: "Quirguistão" },
    { value: "2.9", label: "Laos" },
    { value: "3.0", label: "Letônia" },
    { value: "3.1", label: "Líbano" },
    { value: "3.2", label: "Lesoto" },
    { value: "3.3", label: "Libéria" },
    { value: "3.4", label: "Líbia" },
    { value: "3.5", label: "Liechtenstein" },
    { value: "3.6", label: "Lituânia" },
    { value: "3.7", label: "Luxemburgo" },
    { value: "3.8", label: "Macau" },
    { value: "3.9", label: "Macedônia do Norte" },
    { value: "4.0", label: "Madagáscar" },
    { value: "4.1", label: "Malawi" },
    { value: "4.2", label: "Malásia" },
    { value: "4.3", label: "Maldivas" },
    { value: "4.4", label: "Mali" },
    { value: "4.5", label: "Malta" },
    { value: "4.6", label: "Ilhas Marshall" },
    { value: "4.7", label: "Martinica" },
    { value: "4.8", label: "Mauritânia" },
    { value: "4.9", label: "Maurício" },
    { value: "5.0", label: "Mayotte" },
    { value: "5.1", label: "México" },
    { value: "5.2", label: "Micronésia" },
    { value: "5.3", label: "Moldávia" },
    { value: "5.4", label: "Mônaco" },
    { value: "5.5", label: "Mongólia" },
    { value: "5.6", label: "Montenegro" },
    { value: "5.7", label: "Montserrat" },
    { value: "5.8", label: "Marrocos" },
    { value: "5.9", label: "Moçambique" },
    { value: "6.0", label: "Mianmar (Birmânia)" },
    { value: "6.1", label: "Namíbia" },
    { value: "6.2", label: "Nauru" },
    { value: "6.3", label: "Nepal" },
    { value: "6.4", label: "Países Baixos" },
    { value: "6.5", label: "Nova Caledônia" },
    { value: "6.6", label: "Nova Zelândia" },
    { value: "6.7", label: "Nicarágua" },
    { value: "6.8", label: "Níger" },
    { value: "6.9", label: "Nigéria" },
    { value: "7.0", label: "Niue" },
    { value: "7.1", label: "Ilha Norfolk" },
    { value: "7.2", label: "Ilhas Marianas do Norte" },
    { value: "7.3", label: "Noruega" },
    { value: "7.4", label: "Omã" },
    { value: "7.5", label: "Paquistão" },
    { value: "7.6", label: "Palau" },
    { value: "7.7", label: "Território Palestino Ocupado" },
    { value: "7.8", label: "Panamá" },
    { value: "7.9", label: "Papua-Nova Guiné" },
    { value: "8.0", label: "Paraguai" },
    { value: "8.1", label: "Peru" },
    { value: "8.2", label: "Filipinas" },
    { value: "8.3", label: "Ilhas Pitcairn" },
    { value: "8.4", label: "Polônia" },
    { value: "8.5", label: "Portugal" },
    { value: "8.6", label: "Porto Rico" },
    { value: "8.7", label: "Catar" },
    { value: "8.8", label: "Reunião" },
    { value: "8.9", label: "Romênia" },
    { value: "9.0", label: "Rússia" },
    { value: "9.1", label: "Ruanda" },
    { value: "9.2", label: "São Bartolomeu" },
    { value: "9.3", label: "Santa Helena, Ascensão e Tristão da Cunha" },
    { value: "9.4", label: "São Cristóvão e Nevis" },
    { value: "9.5", label: "Santa Lúcia" },
    { value: "9.6", label: "Saint Martin (parte francesa)" },
    { value: "9.7", label: "São Pedro e Miquelão" },
    { value: "9.8", label: "São Vicente e Granadinas" },
    { value: "9.9", label: "Samoa" },
    { value: "10.0", label: "San Marino" },
    { value: "10.1", label: "São Tomé e Príncipe" },
    { value: "10.2", label: "Arábia Saudita" },
    { value: "10.3", label: "Senegal" },
    { value: "10.4", label: "Sérvia" },
    { value: "10.5", label: "Seicheles" },
    { value: "10.6", label: "Serra Leoa" },
    { value: "10.7", label: "Singapura" },
    { value: "10.8", label: "Eslováquia" },
    { value: "10.9", label: "Eslovênia" },
    { value: "11.0", label: "Ilhas Salomão" },
    { value: "11.1", label: "Somália" },
    { value: "11.2", label: "África do Sul" },
    { value: "11.3", label: "Geórgia do Sul e Ilhas Sandwich do Sul" },
    { value: "11.4", label: "Sudão do Sul" },
    { value: "11.5", label: "Espanha" },
    { value: "11.6", label: "Sri Lanka" },
    { value: "11.7", label: "Sudão" },
    { value: "11.8", label: "Suriname" },
    { value: "11.9", label: "Svalbard e Jan Mayen" },
    { value: "12.0", label: "Suazilândia (Essuatíni)" },
    { value: "12.1", label: "Suécia" },
    { value: "12.2", label: "Suíça" },
    { value: "12.3", label: "Síria" },
    { value: "12.4", label: "Taiwan" },
    { value: "12.5", label: "Tajiquistão" },
    { value: "12.6", label: "Tanzânia" },
    { value: "12.7", label: "Tailândia" },
    { value: "12.8", label: "Timor-Leste" },
    { value: "12.9", label: "Togo" },
    { value: "13.0", label: "Tokelau" },
    { value: "13.1", label: "Tonga" },
    { value: "13.2", label: "Trindade e Tobago" },
    { value: "13.3", label: "Tunísia" },
    { value: "13.4", label: "Turquia" },
    { value: "13.5", label: "Turcomenistão" },
    { value: "13.6", label: "Ilhas Turks e Caicos" },
    { value: "13.7", label: "Tuvalu" },
    { value: "13.8", label: "Uganda" },
    { value: "13.9", label: "Ucrânia" },
    { value: "14.0", label: "Emirados Árabes Unidos" },
    { value: "14.1", label: "Reino Unido" },
    { value: "14.2", label: "Estados Unidos" },
    { value: "14.3", label: "Uruguai" },
    { value: "14.4", label: "Uzbequistão" },
    { value: "14.5", label: "Vanuatu" },
    { value: "14.6", label: "Venezuela" },
    { value: "14.7", label: "Vietnã" },
    { value: "14.8", label: "Wallis e Futuna" },
    { value: "14.9", label: "Saara Ocidental" },
    { value: "15.0", label: "Iémen" },
    { value: "15.1", label: "Zâmbia" },
    { value: "15.2", label: "Zimbábue" },
  ];

  const colourStyles = {
    control: (base) => ({
      ...base,
      border: 0,
      boxShadow: "none",
      padding: "12px 0 12px 35px",
      margin: "-16px 0 0 -45px",
      borderRadius: "0",
      outline: "none",
    }),
  };

  return (
    <React.Fragment>
      <Select
        options={options}
        className="choices selectForm__inner "
        defaultValue={{ label: "Afeganistão", value: 0 }}
        styles={colourStyles}
      />
    </React.Fragment>
  );
};

export default CountryOptions;
